# Generated by Django 3.0.5 on 2020-04-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humedadAire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humedadaire',
            name='type',
        ),
    ]
