# Generated by Django 3.0.5 on 2020-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humedadAire', '0002_remove_humedadaire_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='humedadaire',
            name='type',
            field=models.CharField(default=0, max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
