# Generated by Django 3.0.5 on 2020-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humedadAire', '0004_humedadaire_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='humedadaire',
            name='longitude',
            field=models.CharField(default=1, max_length=20, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humedadaire',
            name='terrain',
            field=models.CharField(default=1, max_length=20, verbose_name='Tipo de Terreno'),
            preserve_default=False,
        ),
    ]
