# Generated by Django 3.0.5 on 2020-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humedadAire', '0006_auto_20200513_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedadaire',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='humedadaire',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
    ]
